version: '3.9'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - security:/var/lib/postgresql
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  security: